apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-lab
labels:
  - pairs:
      app.kubernetes.io/part-of: gateway-api-lab
resources:
  - namespace.yaml
  - httpbin.yaml
  - gateway.yaml
